//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduateThesis.Repository.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraduateThesis.Repository.BLL.Resources.SqlQueryResource", typeof(SqlQueryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP DATABASE {0}
        ///TO DISK = {1}
        ///WITH EXPIREDATE = {2}.
        /// </summary>
        internal static string BackupDb {
            get {
                return ResourceManager.GetString("BackupDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = {0}.
        /// </summary>
        internal static string ClearDbBackupHistory {
            get {
                return ResourceManager.GetString("ClearDbBackupHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///   CONVERT(CHAR(100), SERVERPROPERTY(&apos;Servername&apos;)) AS [Server], 
        ///   msdb.dbo.backupset.[database_name] AS DatabaseName, 
        ///   msdb.dbo.backupset.backup_start_date AS StartDate, 
        ///   msdb.dbo.backupset.backup_finish_date AS FinishDate, 
        ///   msdb.dbo.backupset.expiration_date AS ExpirationDate, 
        ///   CASE msdb..backupset.type 
        ///      WHEN &apos;D&apos; THEN &apos;Database&apos; 
        ///      WHEN &apos;L&apos; THEN &apos;Log&apos; 
        ///      END AS BackupType, 
        ///   msdb.dbo.backupset.backup_size AS BackupSize, 
        ///   msdb.dbo.backupmediafamily.logica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbBackupHistory {
            get {
                return ResourceManager.GetString("DbBackupHistory", resourceCulture);
            }
        }
    }
}
