CREATE TABLE [HUFI_graduate-thesis].dbo.Students (
  ID VARCHAR(50) NOT NULL
 ,Name NVARCHAR(100) NOT NULL
 ,Phone VARCHAR(20) NOT NULL
 ,Email VARCHAR(200) NOT NULL
 ,Address NVARCHAR(400) NOT NULL
 ,Birthday DATE NOT NULL
 ,Avatar VARCHAR(200) NULL
 ,Description NTEXT NULL
 ,StudentClassId VARCHAR(50) NOT NULL
 ,Password NVARCHAR(100) NOT NULL
 ,Salt NVARCHAR(100) NOT NULL
 ,CreatedAt DATETIME NULL
 ,UpdatedAt DATETIME NULL
 ,DeletedAt DATETIME NULL
 ,IsDeleted BIT NOT NULL
 ,CONSTRAINT PK_Students_ID PRIMARY KEY CLUSTERED (ID)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [HUFI_graduate-thesis].dbo.Students
ADD CONSTRAINT FK_Students_StudentClasses_ID FOREIGN KEY (StudentClassId) REFERENCES dbo.StudentClasses (ID)
GO